spring:
  datasource:
    url: jdbc:h2:mem:diary/datasource
    driverClassName: org.h2.Driver
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

    show-sql: true
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test_db
#    username: journalese
#    password: ThePassword
#    driver-class-name: com.mysql.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    database-platform: org.hibernate.dialect.mysql5.MySQL5DatabasePlatform
#    show-sql: true


server:
  port: 9092

